#!/bin/sh

mode="664"
module_dir=/lib/modules/`uname -r`/extra

case "$1" in
        start)
                echo "Loading modules"
		for module in aesdchar; do
			device=$module
			insmod ${module_dir}/${module}.ko $* || exit 1
			echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
			major=$(awk "\$2==\"${module}\" {print \$1}" /proc/devices)
			if [ ! -z ${major} ]; then
				echo "Remove any existing /dev node for /dev/${device}"
				rm -f /dev/${device}
				echo "Add a node for our device at /dev/${device} using mknod"
				mknod /dev/${device} c $major 0
				echo "Change access mode to ${mode}"
				chmod $mode  /dev/${device}
			else
				echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
			fi
		done
                ;;
        stop)
                echo "Unloading modules"
		for module in aesdchar; do
			device=$module
			# invoke rmmod with all arguments we got
			rmmod $module || exit 1

			# Remove stale nodes
			rm -f /dev/${device}
		done
                ;;
        *)
                echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0

